name: Build & Publish (GitHub Pages)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'   # refresh every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch HubSpot posts -> public/posts.json (robust)
  env:
    HUBSPOT_PRIVATE_APP_TOKEN: ${{ secrets.HUBSPOT_PRIVATE_APP_TOKEN }}
    BLOG_BASE: https://hubspot.greenbasketlaundry.com
    HS_LIMIT: '6'
  run: |
    set -Eeuo pipefail
    mkdir -p public
    # Try to build posts.json; if it fails (bad token, 401, etc), create an empty one
    node scripts/fetch_hubspot.mjs || {
      echo "Fetch failed; writing empty JSON so the site still deploys"
      echo '{"count":0,"posts":[]}' > public/posts.json
    }
    # Also place a copy at the site root so either URL works
    cp public/posts.json posts.json || true

    echo "---- DEBUG: file listing ----"
    ls -la
    echo "---- DEBUG: public/ ----"
    ls -la public || true
    echo "---- DEBUG: posts.json head ----"
    head -c 400 public/posts.json || true


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
